var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/summary/route.js")
R.c("server/chunks/[root-of-the-server]__13sy6k6._.js")
R.c("server/chunks/node_modules_next_0.a-w0t._.js")
R.c("server/chunks/node_modules_@anthropic-ai_sdk_0ecvfok._.js")
R.c("server/chunks/node_modules_zod_v4_0rdo3lc._.js")
R.c("server/chunks/node_modules_0ujt_ui._.js")
R.c("server/chunks/[root-of-the-server]__0v6x.k3._.js")
R.c("server/chunks/_next-internal_server_app_api_summary_route_actions_0up9.wj.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/summary/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/summary/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
